//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonferansProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class katilimci_tbl
    {
        public int id { get; set; }
        [DisplayName("Ýsim")]
        public string ad { get; set; }
        [DisplayName("Soyisim")]
        public string soyad { get; set; }
        [DisplayName("Cep Telefonu")]
        public string telefon { get; set; }
        [DisplayName("E-mail")]
        public string email { get; set; }
        [DisplayName("Katýlanan Konferans")]
        public string katilinankonf { get; set; }
        public Nullable<int> konferans_tbl_id { get; set; }
    
        public virtual konferans_tbl konferans_tbl { get; set; }
    }
}
